import type { Metadata } from 'next'
import { Providers } from './components/Providers'
import { TheHeader } from './components/TheHeader'
import './globals.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <meta name="robots" content="noindex,nofollow" />
      </head>
      <body>
        <Providers>
          <TheHeader />
          <main className="main">
            {children}
          </main>
        </Providers>
      </body>
    </html>
  )
}
